In [7]:
import numpy as np
a = np.array([6, 6, 6, 7, 7, 7, 7, 7, 7])
print(a)
print(a[np.random.randint(len(a), size=5)])
print(np.random.randint(6, 8, 5))

[6 6 6 7 7 7 7 7 7]
[6 6 7 7 6]
[6 6 6 7 6]


# Задание 1

В первом случае массив задан вручную, второй массив сгенерирован на основе длины первого, третий массив сгенерирован с заданными тремя параметрами 

# Задание 2

In [9]:
a, b, n = 0.5, 3.5, 4
a + (b-a) * (np.random.randint(1, n+1, size=10) - 1) / (n-1)


array([3.5, 3.5, 1.5, 1.5, 1.5, 0.5, 1.5, 2.5, 1.5, 3.5])

# Задание 3

In [10]:
(sorted(np.random.choice(np.arange(1,76), 5, replace=False)),\
         np.random.randint(15)+1)

([np.int64(7), np.int64(9), np.int64(10), np.int64(20), np.int64(26)], 5)